[package]
name = "twitch-player"
version = "0.1.0"
edition = "2024"

[dependencies]
opensubsonic = "0.4.0"
pollster = "1.0.1"
wgpu = "30.0.0"
winit = "0.30.13"
bytemuck = { version = "1", features = ["derive"] }
axum = "0.8.9"
tower-http = {version = "0.7.0", features = ["fs","trace"] }
tokio = {version = "1.53.1", features = ["full","io-util"]}
axum-extra = {version = "0.12.6" ,features = ["typed-header"]}
futures-util =  { version ="0.3.33", default-features = false, features = ["sink", "std"] }
headers = "0.4.1"
tokio-stream = "0.1.18"
serde_json = "1.0.151"
serde = "1.0.229"
async-stream = "0.3.6"
dotenvy = "0.15.7"
rodio = "0.22.2"
rand = "0.10.2"
libc = "0.2.189"
